language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
install:
- npm install
deploy:
  provider: gae
  project: cs3219-otot-task-b-gae
  keyfile: client-secret.json
  verbosity: warning
  skip_cleanup: true
  on: master
before_install:
- openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv
  -in client-secret.json.enc -out client-secret.json -d
