language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
  - "$HOME/google-cloud-sdk/"
install:
- npm install
before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv
  -in client-secret.json.enc -out client-secret.json -d
  - gcloud auth activate-service-account --key-file client-secret.json
  - gcloud config set project cs3219-otot-task-b-gae

deploy:
  - provider: script
    script:
      - gcloud app deploy
    skip_cleanup: true
    on: master
# before_install:
# - openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv
#   -in client-secret.json.enc -out client-secret.json -d
